"""init schema

Revision ID: 496429a3543a
Revises: 
Create Date: 2026-09-21 00:16:00.598299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '496429a3543a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('atc_code', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=True)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('publisher', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('published_date', sa.String(length=20), nullable=True),
    sa.Column('license_note', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_user_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_user_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_at', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_doctor_user_id'), 'appointments', ['doctor_user_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_user_id'), 'appointments', ['patient_user_id'], unique=False)
    op.create_table('care_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('patient_user_id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'patient_user_id', name='uq_care_assignment')
    )
    op.create_index(op.f('ix_care_assignments_doctor_id'), 'care_assignments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_care_assignments_patient_user_id'), 'care_assignments', ['patient_user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_patient_user_id'), 'chat_sessions', ['patient_user_id'], unique=False)
    op.create_table('drugs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('strength', sa.String(length=80), nullable=True),
    sa.Column('form', sa.String(length=80), nullable=True),
    sa.Column('is_combination', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('in_scope', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drugs_name'), 'drugs', ['name'], unique=True)
    op.create_table('patient_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('dob', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('chronic_conditions', sa.Text(), nullable=True),
    sa.Column('assigned_doctor_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_profiles_user_id'), 'patient_profiles', ['user_id'], unique=True)
    op.create_table('safety_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('rule_version', sa.String(length=20), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('condition_json', sa.Text(), nullable=False),
    sa.Column('required_data_json', sa.Text(), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('next_review_date', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'rule_version', name='uq_rule_code_version')
    )
    op.create_index(op.f('ix_safety_rules_code'), 'safety_rules', ['code'], unique=False)
    op.create_index(op.f('ix_safety_rules_rule_type'), 'safety_rules', ['rule_type'], unique=False)
    op.create_table('allergy_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_profile_id', sa.String(length=36), nullable=False),
    sa.Column('substance', sa.String(length=160), nullable=False),
    sa.Column('reaction', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('verification', sa.String(length=20), nullable=False),
    sa.Column('reported_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('verified_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('onset_date', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergy_records_patient_profile_id'), 'allergy_records', ['patient_profile_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('clinical_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_profile_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=80), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('occurred_at', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verification', sa.String(length=20), nullable=False),
    sa.Column('reported_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_observations_patient_profile_id'), 'clinical_observations', ['patient_profile_id'], unique=False)
    op.create_table('consultation_rooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=False),
    sa.Column('room_code', sa.String(length=60), nullable=False),
    sa.Column('allow_recording', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_code')
    )
    op.create_index(op.f('ix_consultation_rooms_appointment_id'), 'consultation_rooms', ['appointment_id'], unique=True)
    op.create_table('drug_ingredients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('drug_id', sa.String(length=36), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_ingredients_drug_id'), 'drug_ingredients', ['drug_id'], unique=False)
    op.create_index(op.f('ix_drug_ingredients_ingredient_id'), 'drug_ingredients', ['ingredient_id'], unique=False)
    op.create_table('medication_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_profile_id', sa.String(length=36), nullable=False),
    sa.Column('drug_id', sa.String(length=36), nullable=True),
    sa.Column('raw_name', sa.String(length=160), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_planned', sa.Boolean(), nullable=False),
    sa.Column('dose', sa.String(length=80), nullable=True),
    sa.Column('route', sa.String(length=40), nullable=True),
    sa.Column('frequency', sa.String(length=80), nullable=True),
    sa.Column('verification', sa.String(length=20), nullable=False),
    sa.Column('reported_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('source_label', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_records_patient_profile_id'), 'medication_records', ['patient_profile_id'], unique=False)
    op.create_table('safety_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_profile_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('result_status', sa.String(length=30), nullable=False),
    sa.Column('input_snapshot', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_checks_patient_profile_id'), 'safety_checks', ['patient_profile_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('safety_check_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('rule_code', sa.String(length=60), nullable=False),
    sa.Column('rule_version', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_title', sa.String(length=200), nullable=False),
    sa.Column('source_version', sa.String(length=40), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['safety_rules.id'], ),
    sa.ForeignKeyConstraint(['safety_check_id'], ['safety_checks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_safety_check_id'), 'alerts', ['safety_check_id'], unique=False)
    op.create_table('alert_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_user_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_reviews_alert_id'), 'alert_reviews', ['alert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_reviews_alert_id'), table_name='alert_reviews')
    op.drop_table('alert_reviews')
    op.drop_index(op.f('ix_alerts_safety_check_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_safety_checks_patient_profile_id'), table_name='safety_checks')
    op.drop_table('safety_checks')
    op.drop_index(op.f('ix_medication_records_patient_profile_id'), table_name='medication_records')
    op.drop_table('medication_records')
    op.drop_index(op.f('ix_drug_ingredients_ingredient_id'), table_name='drug_ingredients')
    op.drop_index(op.f('ix_drug_ingredients_drug_id'), table_name='drug_ingredients')
    op.drop_table('drug_ingredients')
    op.drop_index(op.f('ix_consultation_rooms_appointment_id'), table_name='consultation_rooms')
    op.drop_table('consultation_rooms')
    op.drop_index(op.f('ix_clinical_observations_patient_profile_id'), table_name='clinical_observations')
    op.drop_table('clinical_observations')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_allergy_records_patient_profile_id'), table_name='allergy_records')
    op.drop_table('allergy_records')
    op.drop_index(op.f('ix_safety_rules_rule_type'), table_name='safety_rules')
    op.drop_index(op.f('ix_safety_rules_code'), table_name='safety_rules')
    op.drop_table('safety_rules')
    op.drop_index(op.f('ix_patient_profiles_user_id'), table_name='patient_profiles')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_drugs_name'), table_name='drugs')
    op.drop_table('drugs')
    op.drop_index(op.f('ix_chat_sessions_patient_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_care_assignments_patient_user_id'), table_name='care_assignments')
    op.drop_index(op.f('ix_care_assignments_doctor_id'), table_name='care_assignments')
    op.drop_table('care_assignments')
    op.drop_index(op.f('ix_appointments_patient_user_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_user_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
