"""triage guides notifications caregiver role expansion

Revision ID: d823fdd70eb0
Revises: 496429a3543a
Create Date: 2026-09-23 09:57:27.835371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd823fdd70eb0'
down_revision: Union[str, Sequence[str], None] = '496429a3543a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregiver_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('caregiver_user_id', sa.String(length=36), nullable=False),
    sa.Column('patient_user_id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caregiver_user_id', 'patient_user_id', name='uq_caregiver_link')
    )
    op.create_index(op.f('ix_caregiver_links_caregiver_user_id'), 'caregiver_links', ['caregiver_user_id'], unique=False)
    op.create_index(op.f('ix_caregiver_links_patient_user_id'), 'caregiver_links', ['patient_user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('for_role', sa.String(length=20), nullable=True),
    sa.Column('for_user_id', sa.String(length=36), nullable=True),
    sa.Column('patient_profile_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['for_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_for_role'), 'notifications', ['for_role'], unique=False)
    op.create_index(op.f('ix_notifications_for_user_id'), 'notifications', ['for_user_id'], unique=False)
    op.create_table('suspect_rankings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_profile_id', sa.String(length=36), nullable=False),
    sa.Column('reaction_description', sa.Text(), nullable=False),
    sa.Column('ranked_json', sa.Text(), nullable=False),
    sa.Column('basis_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confirmed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suspect_rankings_patient_profile_id'), 'suspect_rankings', ['patient_profile_id'], unique=False)
    op.create_table('medication_guides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_profile_id', sa.String(length=36), nullable=False),
    sa.Column('medication_id', sa.String(length=36), nullable=True),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('ai_draft_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('drafted_by', sa.String(length=20), nullable=True),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('acknowledgment', sa.String(length=20), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medication_records.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_guides_patient_profile_id'), 'medication_guides', ['patient_profile_id'], unique=False)
    op.create_table('triage_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_profile_id', sa.String(length=36), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('matched_rules', sa.Text(), nullable=True),
    sa.Column('rules_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confirmed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['clinical_observations.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_assessments_patient_profile_id'), 'triage_assessments', ['patient_profile_id'], unique=False)
    op.add_column('medication_records', sa.Column('timing', sa.String(length=120), nullable=True))
    op.add_column('medication_records', sa.Column('start_date', sa.String(length=20), nullable=True))
    op.add_column('medication_records', sa.Column('prescriber', sa.String(length=120), nullable=True))
    op.add_column('medication_records', sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
    op.add_column('medication_records', sa.Column('stop_reason', sa.String(length=200), nullable=True))
    op.add_column('medication_records', sa.Column('last_reaction', sa.String(length=300), nullable=True))
    op.add_column('medication_records', sa.Column('image_url', sa.String(length=300), nullable=True))
    op.add_column('patient_profiles', sa.Column('diagnosis', sa.Text(), nullable=True))
    op.add_column('patient_profiles', sa.Column('admission_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_profiles', 'admission_note')
    op.drop_column('patient_profiles', 'diagnosis')
    op.drop_column('medication_records', 'image_url')
    op.drop_column('medication_records', 'last_reaction')
    op.drop_column('medication_records', 'stop_reason')
    op.drop_column('medication_records', 'status')
    op.drop_column('medication_records', 'prescriber')
    op.drop_column('medication_records', 'start_date')
    op.drop_column('medication_records', 'timing')
    op.drop_index(op.f('ix_triage_assessments_patient_profile_id'), table_name='triage_assessments')
    op.drop_table('triage_assessments')
    op.drop_index(op.f('ix_medication_guides_patient_profile_id'), table_name='medication_guides')
    op.drop_table('medication_guides')
    op.drop_index(op.f('ix_suspect_rankings_patient_profile_id'), table_name='suspect_rankings')
    op.drop_table('suspect_rankings')
    op.drop_index(op.f('ix_notifications_for_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_for_role'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_caregiver_links_patient_user_id'), table_name='caregiver_links')
    op.drop_index(op.f('ix_caregiver_links_caregiver_user_id'), table_name='caregiver_links')
    op.drop_table('caregiver_links')
    # ### end Alembic commands ###
